services:
  mongo:
    image: mongo:7
    container_name: taskmanager-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - taskmanager-net

  app:
    image: neell369/task-manager:latest   # use prebuilt image from Docker Hub
    # build: . 
    container_name: taskmanager-app
    restart: always
    env_file:
      - ../.env
    depends_on:
      - mongo
    networks:
      - taskmanager-net

  nginx:
    image: nginx:latest
    container_name: taskmanager-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - taskmanager-net

  mongo-express:
    image: mongo-express:1.0.0
    container_name: taskmanager-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - taskmanager-net

volumes:
  mongo-data:

networks:
  taskmanager-net:
    name: taskmanager_network
    driver: bridge
